### ISSUE TITLE
Documentation of OMAA data structures and RO-Crate representations

### ISSUE THREAD

**Issue by spikelynch** [Sydney-Informatics-Hub/Heurist-Integration#3]

**Comment by IanMcCrabb** [comment]
Attached is a draft analysis report with regard to options for mapping Heurist data structures to RO-Crate

https://docs.google.com/document/d/1bPIUhK9RNUbpEHb41Ej5u_9Im1sUL-ec/edit?usp=drive_link&ouid=114283746704550259146&rtpof=true&sd=true

**Comment by IanMcCrabb** [comment]
Have uploaded an updated analysis report for discussion on Friday.

**Comment by IanMcCrabb** [comment]
Have uploaded an updated analysis report which now includes a draft specification for crosswalk to RO Crate.

https://docs.google.com/document/d/1Ssf3okJ3zTN5f25ULmCUz7SIOzLxrmV1/edit?usp=drive_link&ouid=114283746704550259146&rtpof=true&sd=true
